version: '3'

services:
  about:
    build: ./src/about
    volumes:
      - ./src/about:/app

  global-navigation:
    build: ./src/global-navigation
    ports:
      - 3001:80

  homepage:
    build: ./src/homepage
    volumes:
      - ./src/homepage:/app

  reverse-proxy:
    build: ./src/reverse-proxy
    depends_on:
      - about
      - global-navigation
      - homepage
    ports:
      - 443:443
      - 80:80
