version: '3'

services:
  about:
    build: ./src/about
    ports:
      - 3000:3000
    volumes:
      - ./src/about:/app

  homepage:
    build: ./src/homepage
    volumes:
      - ./src/homepage:/app

  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/nginx:/etc/nginx/conf.d
    depends_on:
      - about
      - homepage
