version: '3'

services:
  about:
    build: ./src/about
    ports:
      - 3000:3000
    volumes:
      - ./src/about:/app

  homepage:
    build: ./src/homepage
    volumes:
      - ./src/homepage:/app

  reverse-proxy:
    build: ./src/reverse-proxy
    depends_on:
      - about
      - homepage
    ports:
      - 443:443
      - 80:80
